CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS users (
    id UUID DEFAULT uuid_generate_v4(),
    login VARCHAR(512) NOT NULL,
    email VARCHAR(512) NOT NULL,
    password VARCHAR(256) NOT NULL,
    name VARCHAR(256),
    about TEXT,
    phone VARCHAR(20),
    avatar VARCHAR(2048) NOT NULL DEFAULT 'no_avatar.jpg',
    CONSTRAINT PK_USER PRIMARY KEY (id),
    CONSTRAINT FK_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS genres (
    id UUID DEFAULT uuid_generate_v4(),
    name VARCHAR(256),
    CONSTRAINT PK_GENRE PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS authors (
    id UUID DEFAULT uuid_generate_v4(),
    first_name VARCHAR(256),
    last_name VARCHAR(256),
    middle_name VARCHAR(256),
    CONSTRAINT PK_AUTHOR PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS books (
    id UUID DEFAULT uuid_generate_v4(),
    title VARCHAR(512),
    description TEXT,
    isbn VARCHAR(512),
    cover VARCHAR(2048) DEFAULT 'no_cover.jpg',
    CONSTRAINT PK_BOOK PRIMARY KEY (id),
    CONSTRAINT UQ_BOOK_ISBN UNIQUE (isbn)
);

CREATE TABLE IF NOT EXISTS book_genres (
    id UUID DEFAULT uuid_generate_v4(),
    book_id UUID NOT NULL,
    genre_id UUID NOT NULL,
    CONSTRAINT PK_BOOK_GENRE PRIMARY KEY (id),
    CONSTRAINT FK_BOOK_FOR_BOOK_GENRES FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE RESTRICT,
    CONSTRAINT FK_GENRE_FOR_BOOK_GENRES FOREIGN KEY (genre_id) REFERENCES genres (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS book_authors (
    id UUID DEFAULT uuid_generate_v4(),
    book_id UUID NOT NULL,
    author_id UUID NOT NULL,
    CONSTRAINT PK_BOOK_AUTHOR PRIMARY KEY (id),
    CONSTRAINT FK_BOOK_FOR_BOOK_AUTHORS FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE RESTRICT,
    CONSTRAINT FK_AUTHOR_FOR_BOOK_AUTHORS FOREIGN KEY (author_id) REFERENCES authors (id) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS bookcrossing_points (
    id UUID DEFAULT uuid_generate_v4(),
    title VARCHAR(512) NOT NULL DEFAULT '',
    latitude FLOAT NOT NULL DEFAULT 0,
    longitude FLOAT NOT NULL DEFAULT 0,
    address_text TEXT NOT NULL DEFAULT '',
    CONSTRAINT PK_BOOKCROSSING_POINT PRIMARY KEY (id)
);